Logging:
    default: TRACE

General:
    Modus:          List
    Time_Step_Mode: Fixed
    End_Time:       250.0
    Randomseed:     -1
    Cross_Section_Scaling_Factor:
        Type: File

Modi:
    List:
        Optional_Quantities: ["ID", "charge", "begin_form_time", "xsecfac"]

Output:
    Output_Interval: 50.0
    Particles:
        Format: ["HepMC_asciiv3", "Oscar2013"]
        Extended: True
    Collisions:
        Format: ["HepMC_asciiv3", "Oscar2013"]