Logging:
    default: TRACE

General:
    Modus:          List
    Time_Step_Mode: Fixed
    End_Time:       250.0
    Randomseed:     -1

Modi:
    List:
        Optional_Quantities: ["ID", "charge", "begin_form_time", "xsecfac"]

Output:
    Output_Interval: 50.0
    Particles:
        Format: ["Oscar2013"]
        Extended: True

Collision_Term:
    Cross_Section_Formation_Scaling:
        Profile:
            Formation_Time: 1.0